export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const GET_NUMBER_BASKET = "GET_NUMBER_BASKET";
export const UPDATE_CART = "UPDATE_CART";

export const GET_TOKEN = "GET_TOKEN";
export const ADD_TOKEN = "ADD_TOKEN";
export const DELETE_TOKEN = "DELETE_TOKEN";

export const GET_TOKEN_ADMIN = "GET_TOKEN_ADMIN";
export const ADD_TOKEN_ADMIN = "ADD_TOKEN_ADMIN";
export const DELETE_TOKEN_ADMIN = "DELETE_TOKEN_ADMIN";

export const UPDATE_INFO = "UPDATE_INFO";
